# Generated by Django 3.1.2 on 2020-10-15 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stickers', '0002_remove_sticker_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='sticker',
            name='board',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='board_stickers', to='stickers.board'),
            preserve_default=False,
        ),
    ]
